import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { constructMetadata } from '@/lib/metadata';
import { constructSoftwareAppSchema } from '@/lib/schema';
import { Container } from '@/components/ui/Container';
import { Section } from '@/components/ui/Section';
import { PageHeader } from '@/components/ui/PageHeader';
import { Breadcrumbs } from '@/components/ui/Breadcrumbs';
import { FAQ, FAQItem } from '@/components/ui/FAQ';
import { AdPlaceholder } from '@/components/ui/AdPlaceholder';
import { TranscriptionWorkspace } from '@/components/tools/TranscriptionWorkspace';
import { InfoSection, StepsSection, CrossLinks, InfoCard } from '@/components/tools/ToolInfoSections';
import { JsonLd } from '@/components/JsonLd';
import { siteConfig } from '@/config/site';
import { FileAudio, Upload, Clock, Languages, FileDown, ShieldCheck } from 'lucide-react';

export const metadata: Metadata = constructMetadata({
  title: 'Free Audio to Text Converter | Timestamps & SRT Export',
  description:
    'Convert audio and video to text online with accurate timestamps. Export transcripts to TXT, SRT, VTT, and JSON with sentence, paragraph, or word-level sync.',
  path: '/audio-to-text',
});

export default function AudioToTextPage() {
  const pageUrl = `${siteConfig.url}/audio-to-text`;

  const webAppSchema = constructSoftwareAppSchema({
    name: 'Konthora Audio to Text with Timestamps',
    url: pageUrl,
  });

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: siteConfig.url },
      { '@type': 'ListItem', position: 2, name: 'Audio to Text', item: pageUrl },
    ],
  };

  const audioFaqs: FAQItem[] = [
    {
      question: 'What is the maximum upload file size?',
      answer:
        'The maximum file size per upload is 100 MB. For longer recordings, files must also be within a 10-minute duration limit.',
    },
    {
      question: 'Which file formats are supported for transcription?',
      answer:
        'Konthora accepts MP3, WAV, M4A, AAC, MP4, WebM, and MOV files. Video files are processed for their audio track only.',
    },
    {
      question: 'Which languages are supported?',
      answer:
        'Konthora currently transcribes English-language audio. Selecting "Auto Detect" also processes the audio as English.',
    },
    {
      question: 'How accurate are the timestamps?',
      answer:
        'Timestamps are generated by the Whisper speech recognition model. You can choose sentence-level, paragraph-level, or word-level timestamp grouping for your use case.',
    },
    {
      question: 'What export formats are available?',
      answer:
        'You can export your transcript as plain TXT, SRT subtitle format, WebVTT caption format, or structured JSON containing segments and, in word mode, word-level timing data.',
    },
    {
      question: 'Are uploaded files stored permanently?',
      answer:
        'No. Uploaded media files and generated transcripts are automatically deleted 60 minutes after processing. Nothing is retained beyond that window.',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: audioFaqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  };

  const capabilityCards: InfoCard[] = [
    {
      icon: Upload,
      title: '7 file formats',
      desc: 'Upload MP3, WAV, M4A, AAC, MP4, WebM, or MOV. Video files are read for their audio track.',
    },
    {
      icon: Clock,
      title: 'Caps for size and length',
      desc: 'Transcribe files up to 100 MB, and recordings up to 10 minutes long, in one job.',
    },
    {
      icon: Languages,
      title: 'English input',
      desc: 'Accurate transcription for English-language audio that you can verify in your browser.',
    },
    {
      icon: FileDown,
      title: 'TXT, SRT, VTT, JSON',
      desc: 'Export clean text, subtitles for players, or segmented JSON for editing.',
    },
  ];

  const useCaseCards: InfoCard[] = [
    {
      icon: FileAudio,
      title: 'Interviews & podcasts',
      desc: 'Turn recorded conversations into searchable, timestamped notes you can quote.',
    },
    {
      icon: FileDown,
      title: 'Captions & subtitles',
      desc: 'Export SRT or VTT to add accurate captions to your videos.',
    },
    {
      icon: Languages,
      title: 'Meetings & lectures',
      desc: 'Keep a written record of talks, briefings, and brainstorming sessions.',
    },
    {
      icon: ShieldCheck,
      title: 'Research & analysis',
      desc: 'Quote key moments with confidence using word- and sentence-level timestamps.',
    },
  ];

  const steps = [
    {
      title: 'Upload an audio or video file',
      desc: 'Drop in an MP3, WAV, or other listed format, up to 100 MB.',
    },
    {
      title: 'Choose timestamp grouping',
      desc: 'Pick sentence-, paragraph-, or word-level detail for your transcript.',
    },
    {
      title: 'Transcribe, review, and export',
      desc: 'Review the timestamped transcript, then download it as TXT, SRT, VTT, or JSON.',
    },
  ];

  return (
    <>
      <JsonLd schema={webAppSchema} />
      <JsonLd schema={breadcrumbSchema} />
      <JsonLd schema={faqSchema} />

      <Section className="pb-4">
        <Container>
          <Breadcrumbs items={[{ name: 'Home', href: '/' }, { name: 'Audio to Text' }]} />
          <PageHeader
            title="Audio to Text with Timestamps"
            description="Upload audio or media, choose sentence, paragraph, or word-level timestamps, then transcribe, review, and export as TXT, SRT, VTT, or JSON."
            badge="Transcription"
          />
          <TranscriptionWorkspace />
          <AdPlaceholder />
        </Container>
      </Section>

      <InfoSection
        id="capabilities"
        eyebrow="Capabilities"
        title="Everything the transcription workspace supports"
        description="Konthora turns English speech into accurate, timestamped text ready to edit and export. Here is exactly what is supported."
        cards={capabilityCards}
        compact
      />

      <StepsSection
        id="how-to-transcribe"
        eyebrow="How it works"
        title="Transcribe audio in three steps"
        description="Upload a file and get an accurate, timestamped transcript in seconds."
        steps={steps}
        compact
      />

      <InfoSection
        id="use-cases"
        eyebrow="Who it is for"
        title="How people use Konthora transcription"
        description="Timestamped transcripts for talking, research, and content production."
        cards={useCaseCards}
        twoCol
        compact
      />

      <CrossLinks
        title="Related tools"
        description="Pair transcription with speech generation to keep your audio workflow in one place."
        links={[
          {
            href: siteConfig.links.textToSpeech,
            label: 'Free AI Text to Speech',
            description:
              'Turn text into natural speech with 41 AI voices across six languages, and download as MP3 or WAV.',
            primary: true,
          },
          {
            href: '/speech-to-text/timestamps',
            label: 'Transcription Timestamps Guide',
            description: 'Compare sentence, paragraph, and word-level grouping before you transcribe.',
          },
        ]}
        compact
      />

      {/* ── Explore Guides ── */}
      <Section aria-labelledby="explore-guides-heading" className="py-10 md:py-12">
        <Container>
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="text-2xl font-bold text-foreground sm:text-3xl" id="explore-guides-heading">
              Explore Audio Transcription Guides
            </h2>
          </div>
          
          <div className="mt-8">
            <h3 className="text-lg font-semibold text-foreground mb-4">Learn the workflow</h3>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              {[
                {
                  href: '/speech-to-text',
                  label: 'Speech to Text Overview',
                  description: 'Learn how automatic speech recognition converts spoken words into text.',
                },
                {
                  href: '/speech-to-text/how-to-transcribe-audio',
                  label: 'How to Transcribe Audio',
                  description: 'A step-by-step walkthrough on turning any audio file into text.',
                },
                {
                  href: '/speech-to-text/timestamps',
                  label: 'Transcription Timestamps',
                  description: 'Understand the difference between sentence, paragraph, and word-level timing.',
                },
                {
                  href: '/speech-to-text/audio-transcription-accuracy',
                  label: 'Audio Transcription Accuracy',
                  description: 'Discover what factors affect the results of speech-to-text software.',
                },
              ].map((l) => (
                <Link
                  key={l.href}
                  href={l.href}
                  className="group rounded-xl border border-border/70 bg-card p-4 shadow-card transition-all duration-200 hover:-translate-y-1 hover:border-primary/25"
                >
                  <div className="font-semibold text-foreground group-hover:text-primary transition-colors">
                    {l.label}
                  </div>
                  <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{l.description}</p>
                  <span className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-primary">
                    Read guide
                    <svg className="h-4 w-4 transition-transform group-hover:translate-x-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4-4 4M21 12H3" />
                    </svg>
                  </span>
                </Link>
              ))}
            </div>
          </div>

          <div className="mt-8">
            <h3 className="text-lg font-semibold text-foreground mb-4">Explore practical use cases</h3>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              {[
                {
                  href: '/transcribe-podcast',
                  label: 'Podcast Transcription',
                  description: 'Convert podcast episodes into searchable show notes and blogs.',
                },
                {
                  href: '/transcribe-interview',
                  label: 'Interview Transcription',
                  description: 'Turn recorded interviews into accurate text for research or journalism.',
                },
                {
                  href: '/transcribe-meeting',
                  label: 'Meeting Transcription',
                  description: 'Generate written records of business meetings and conference calls.',
                },
                {
                  href: '/transcribe-lecture',
                  label: 'Lecture Transcription',
                  description: 'Transcribe academic lectures and seminars for easier studying.',
                },
                {
                  href: '/transcribe-video',
                  label: 'Video Transcription',
                  description: 'Extract and transcribe dialogue from MP4, WebM, and MOV files.',
                },
{
                  href: '/transcribe-voice-memo',
                  label: 'Voice Memo Transcription',
                  description: 'Turn personal voice notes and quick ideas into written text.',
                },
                {
                  href: '/mp3-to-text',
                  label: 'MP3 to Text Converter',
                  description: 'Convert MP3 audio files into timestamped transcripts quickly.',
                },
                {
                  href: '/video-to-text',
                  label: 'Video to Text Converter',
                  description: 'Transcribe the audio track from MP4, WebM, and MOV videos.',
                },
                {
                  href: '/transcribe-webinar',
                  label: 'Webinar Transcription',
                  description: 'Create text transcripts of recorded webinars for accessibility.',
                },
              ].map((l) => (
                <Link
                  key={l.href}
                  href={l.href}
                  className="group rounded-xl border border-border/70 bg-card p-4 shadow-card transition-all duration-200 hover:-translate-y-1 hover:border-primary/25"
                >
                  <div className="font-semibold text-foreground group-hover:text-primary transition-colors">
                    {l.label}
                  </div>
                  <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{l.description}</p>
                  <span className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-primary">
                    Read guide
                    <svg className="h-4 w-4 transition-transform group-hover:translate-x-1" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4-4 4M21 12H3" />
                    </svg>
                  </span>
                </Link>
              ))}
            </div>
          </div>
        </Container>
      </Section>

      {/* Tool FAQ Section */}
      <Section className="bg-secondary/10 py-10 md:py-12">
        <Container>
          <div className="text-center mb-8" id="a2t-faq-heading">
            <h2 className="text-2xl font-bold text-foreground">Transcription FAQs</h2>
            <p className="mt-2 text-muted-foreground">Common questions about Konthora&apos;s audio transcription tool.</p>
          </div>
          <FAQ items={audioFaqs} />
        </Container>
      </Section>
    </>
  );
}
